locale: "en-US"
title: "Mojgan Samandar A. E. - Economist & Data Analyst"
description: "Ph.D. Economist | Big Data Analyst | Researcher | Policy & BI Consultant"
url: "https://samandarali.github.io"
baseurl: ""   # keep empty for user.github.io sites
repository: "samandarali/samandarali.github.io"

# Use the AcademicPages theme (built on Minimal Mistakes)
remote_theme: academicpages/academicpages@v0.8.4

# Plugins supported by GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Author / sidebar
author:
  avatar: "/images/Samandar Ali Eshtehardi-Mojgan-PR photo.jpg"
  name: "Mojgan Samandar A. E."
  pronouns: "she/her"
  bio: "Ph.D. Economist | Big Data Analyst | Researcher | Policy & BI Consultant"
  location: "Ontario, Canada"
  email: "mojgan.samandar@outlook.com"
  linkedin: "mojgan-samandar"
  googlescholar: "https://scholar.google.ca/citations?hl=en&user=fYvemsMAAAAJ"
  orcid: "https://orcid.org/0000-0001-5770-7398"
  github: "samandarali"

# Site imagery
teaser: "/images/header.jpg"  # optional; replace if you have this
og_image: "/images/Samandar Ali Eshtehardi-Mojgan-PR photo.jpg"

# Feeds & SEO
atom_feed:
  hide: false

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Build
markdown: kramdown
highlighter: rouge

# Timezone
timezone: America/Toronto
